# Streamlit Configuration File
# GitHub Light Theme Configuration

[theme]
# Primary accent color for interactive elements
primaryColor = "#0969da"  # GitHub blue

# Background color for the main content area
backgroundColor = "#ffffff"  # Pure white

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#f6f8fa"  # GitHub light grey

# Color used for almost all text
textColor = "#24292f"  # GitHub dark text


[server]
# Enable static file serving
enableStaticServing = true

# Enable CORS for all origins
enableCORS = true

# Run on all network interfaces
headless = true

[browser]
# Server address
serverAddress = "localhost"

# Server port
serverPort = 8501

# Don't automatically open browser on start
gatherUsageStats = false

[runner]
# Streamlit module to run
# main = "app"

[client]
# Controls whether uncaught app exceptions are displayed in the browser.
showErrorDetails = true
